@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%" == "" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if "%ERRORLEVEL%" == "0" goto execute

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:execute
@rem Setup the command line

@rem ---------------------------------------------------------------------------
@rem Zafiro local patch: auto-detect the Windows system proxy.
@rem Proxy enabled in the registry -> Gradle goes through it; otherwise nothing
@rem changes and Gradle goes direct. An explicit proxy in GRADLE_OPTS wins.
@rem NOTE: this file is generated by "gradle wrapper"; regenerating drops this.
@rem ---------------------------------------------------------------------------
set "ZAFIRO_PROXY_HOST="
set "ZAFIRO_PROXY_PORT="
set "ZAFIRO_PROXY_ARGS="

@rem Set ZAFIRO_NO_PROXY=1 to force a direct connection.
if defined ZAFIRO_NO_PROXY goto zafiroProxyDone

set "ZAFIRO_PROXY_ENABLE="
set "ZAFIRO_PROXY_SERVER="
for /f "tokens=3" %%a in ('reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable 2^>NUL ^| findstr /i "ProxyEnable"') do set "ZAFIRO_PROXY_ENABLE=%%a"
if not "%ZAFIRO_PROXY_ENABLE%"=="0x1" goto zafiroProxyDone
for /f "tokens=3" %%a in ('reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyServer 2^>NUL ^| findstr /i "ProxyServer"') do set "ZAFIRO_PROXY_SERVER=%%a"
if "%ZAFIRO_PROXY_SERVER%"=="" goto zafiroProxyDone

@rem ProxyServer is "host:port" or the per-scheme form
@rem "http=host:port;https=host:port"; reduce both to host:port.
set "ZAFIRO_PROXY_HP=%ZAFIRO_PROXY_SERVER%"
for /f "tokens=1 delims=;" %%a in ("%ZAFIRO_PROXY_SERVER%") do set "ZAFIRO_PROXY_HP=%%a"
for /f "tokens=1,* delims==" %%a in ("%ZAFIRO_PROXY_HP%") do if not "%%b"=="" set "ZAFIRO_PROXY_HP=%%b"
for /f "tokens=1,2 delims=:" %%a in ("%ZAFIRO_PROXY_HP%") do (
  set "ZAFIRO_PROXY_HOST=%%a"
  set "ZAFIRO_PROXY_PORT=%%b"
)
if "%ZAFIRO_PROXY_HOST%"=="" goto zafiroProxyDone
if "%ZAFIRO_PROXY_PORT%"=="" goto zafiroProxyDone

@rem GRADLE_OPTS covers the wrapper JVM, which downloads the distribution.
@rem ZAFIRO_PROXY_ARGS is also passed as program arguments below, which is what
@rem reaches the Gradle client and gets forwarded to the daemon.
set "ZAFIRO_PROXY_ARGS=-Dhttp.proxyHost=%ZAFIRO_PROXY_HOST% -Dhttp.proxyPort=%ZAFIRO_PROXY_PORT% -Dhttps.proxyHost=%ZAFIRO_PROXY_HOST% -Dhttps.proxyPort=%ZAFIRO_PROXY_PORT% -Dhttp.nonProxyHosts=localhost"
@rem Prepended: an explicit proxy already in GRADLE_OPTS still wins.
set "GRADLE_OPTS=%ZAFIRO_PROXY_ARGS% %GRADLE_OPTS%"
@rem pip (Chaquopy requirements) reads these; the JVM does not.
if not defined HTTP_PROXY set "HTTP_PROXY=http://%ZAFIRO_PROXY_HOST%:%ZAFIRO_PROXY_PORT%"
if not defined HTTPS_PROXY set "HTTPS_PROXY=%HTTP_PROXY%"
echo Using system proxy %ZAFIRO_PROXY_HOST%:%ZAFIRO_PROXY_PORT% for Gradle.

:zafiroProxyDone
set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar


@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %ZAFIRO_PROXY_ARGS% %*

:end
@rem End local scope for the variables with windows NT shell
if "%ERRORLEVEL%"=="0" goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
if  not "" == "%GRADLE_EXIT_CONSOLE%" exit 1
exit /b 1

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega